name: Docker Image CI BackeNd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - name: 💣 Nuke ghost src directory (if it exists)
        run: |
          rm -rf backend/src
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Show dependencies.py contents
        run: |
          cat backend/app/dependencies.py
      - name: Show contest.py contents
        run: |
          cat backend/tests/conftest.py
      - name: Second check
        run: |
          cat /home/runner/work/journal/journal/backend/tests/conftest.py
            
      
      - name: Remove Python cache
        run: |
          echo "🧹 Cleaning all .pyc and __pycache__ folders"
          find . -type d -name "__pycache__" -exec rm -r {} +
          find . -type f -name "*.pyc" -delete
      - name: Debug Python files
        run: |
          find . -name "config.py"
          grep -r "read_file" .

      - name: Run Single Backend Test
        env:
          TESTING: "true"
          DB_HOST: localhost
        run: |
          cd backend
          pytest tests/test_users.py::test_create_user --maxfail=1 --disable-warnings -q
        
      - name: Show Test Results Summary
        if: always()
        run: |
          echo "✅ Tests completed. See logs for details."
